---
- apt_repository:
     repo: ppa:ondrej/php


- name: Install php7.3
  apt:
    name: 
        - php7.3
    state: present
    update_cache: yes

- name: Install packages
  apt:
    name: 
        - php7.3-cli
        - php7.3-fpm
        - php7.3-xml
        - php7.3-json
        - php7.3-mysql
        - php7.3-sqlite3
        - php7.3-zip
        - php7.3-gd
        - php7.3-mbstring
        - php7.3-curl
        - php7.3-xml
        - php7.3-bcmath
        - php7.3-pgsql
        - debconf
        - debhelper
        - lintian
        - dh-make
        - hashdeep
        - build-essential
        - libpcre3
        - libpcre3-dev
        - libcurl4-openssl-dev
        - gcc
        - libssl-dev
        - zlib1g-dev
        - python3-psycopg2
        - python-psycopg2
    state: present
    update_cache: yes
  tags: packages


- name: remove packages
  apt:
     name:
        - apache2
     state: absent

- include_tasks: variables.yml
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
#- include_tasks: initialize.yml
- include_tasks: configure.yml
  tags: uss

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"


